# These are supported funding model platforms

github: Giingu
patreon: nezukobot
open_collective: # Replace with a single Open Collective username
ko_fi: nezukobot
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: DBM-Extended
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://buymeacoffee.com/officialnezuko']
