blank_issues_enabled: false
contact_links:
  - name: DBM Network Discord server
    url: https://discord.gg/3QxkZPK
    about: Please use this Discord Server to ask questions and get support. We don't typically answer questions here and they will likely be closed and redirected to the Discord server.
